import { Logger } from 'pino';
import Opossum from 'opossum';
import { Decimal } from 'decimal.js';
import { randomUUID } from 'crypto';
import { 
  InventorySnapshot, 
  StockReconciled, 
  ReconciliationRecordSchema 
} from '../../schemas/inventory_schemas';
import { ReconciliationCacheManager } from '../../cache/reconciliationCacheManager';

/**
 * Expected inventory state derived from event log replay.
 */
export interface ExpectedInventoryState {
  productId: string;
  totalStock: number;
  reservedStock: number;
}

/**
 * Audit result generated by the DiscrepancyAuditorEngine.
 */
export interface AuditResult {
  isConsistent: boolean;
  driftAmount: number;
  reconciliationRecord: any;
}

/**
 * Custom error for critical inconsistencies found during reconciliation.
 */
export class CriticalInconsistencyError extends Error {
  constructor(public message: string, public productId: string, public drift: number) {
    super(message);
    this.name = 'CriticalInconsistencyError';
  }
}

/**
 * The DiscrepancyAuditorEngine performs rigorous reconciliation between
 * the persistent database state and event-sourced expected state.
 */
export class DiscrepancyAuditorEngine {
  private readonly breaker: Opossum;
  private readonly driftThreshold = new Decimal('0.00'); // Configurable business policy

  constructor(
    private readonly logger: Logger,
    private readonly cacheManager: ReconciliationCacheManager
  ) {
    this.logger = this.logger.child({ module: 'services/reconciliation/auditor' });

    // Circuit breaker for audit operations
    this.breaker = new Opossum(async (fn: () => Promise<AuditResult>) => await fn(), {
      timeout: 5000,
      errorThresholdPercentage: 50,
      resetTimeout: 30000,
    });
  }

  /**
   * Performs the comparison logic between actual and expected inventory.
   */
  public async audit(
    actual: InventorySnapshot,
    expected: ExpectedInventoryState
  ): Promise<AuditResult> {
    return await this.breaker.fire(async () => {
      const actualTotal = new Decimal(actual.total_stock);
      const expectedTotal = new Decimal(expected.totalStock);
      const drift = actualTotal.minus(expectedTotal);

      const isConsistent = drift.equals(this.driftThreshold);

      const record = {
        reconciliation_id: randomUUID(),
        product_id: actual.product_id,
        status: isConsistent ? 'SUCCESS' : 'DISCREPANCY_FOUND',
        detected_at: new Date(),
        audit_details: {
          expected_total: expected.totalStock,
          actual_total: actual.total_stock,
          drift_amount: drift.toNumber(),
        },
      };

      const validatedRecord = ReconciliationRecordSchema.parse(record);

      if (!isConsistent) {
        this.logger.warn({
          msg: 'Drift detected in inventory reconciliation',
          productId: actual.product_id,
          drift: drift.toString(),
          details: validatedRecord
        });

        // Threshold check for critical escalation
        if (Math.abs(drift.toNumber()) > 100) { // Example business policy
          this.logger.error({
            msg: 'CRITICAL_INCONSISTENCY',
            productId: actual.product_id,
            drift: drift.toString()
          });
          throw new CriticalInconsistencyError('Critical stock drift detected', actual.product_id, drift.toNumber());
        }
      }

      return {
        isConsistent,
        driftAmount: drift.toNumber(),
        reconciliationRecord: validatedRecord,
      };
    });
  }

  /**
   * Processes a full reconciliation cycle for a product.
   */
  public async reconcile(
    actual: InventorySnapshot,
    expected: ExpectedInventoryState
  ): Promise<StockReconciled> {
    const lockAcquired = await this.cacheManager.lockSkuRange(actual.product_id);
    if (!lockAcquired) {
      throw new Error(`Unable to acquire lock for product ${actual.product_id}`);
    }

    try {
      const result = await this.audit(actual, expected);

      return {
        header: {
          idempotencyKey: randomUUID(),
          timestamp: new Date().toISOString(),
          version: '1.0.0',
        },
        payload: {
          productId: actual.product_id,
          previousTotal: actual.total_stock,
          newTotal: expected.totalStock,
          discrepancyDetected: !result.isConsistent,
        },
      };
    } finally {
      await this.cacheManager.releaseSkuRange(actual.product_id);
    }
  }
}
